name: pdf-compile

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: interview-question.tex
        latexmk_use_xelatex: true


